@startuml
package 0 <<Folder>> {
Class 0.Estado {
}
Class 0.Profesor {
}
Class 0.EstadoRep {
}
Class 0.ConsultaProfesorController {
}
Class 0.ProfesoresController {
}
Class 0.ModificarProfesor {
}
Class 0.ModificarAsesores {
}
Class 0.ProcessorProfesor {
}
Class 0.Turno {
}
Class 0.Genero {
}
Class 0.Grado_profesor {
}
Class 0.ProfesorRep {
}
Class 0.ReaderProfesor {
}
Class 0.GeneroRep {
}
Class 0.Grado_profesorRep {
}
Class 0.TurnoRep {
}
Class 0.ProfesorDto {
}
Class 0./DTO/Inscripcion {
}
Class 0.Request/Impl/InscripcionRequestImpl {
}
Class 0./DTO/Certificado {
}
Class 0.Request/Impl/CertificadoRequestImpl {
}
Class 0./DTO/Grupo {
}
Class 0.Interface/GrupoRepImpl {
}
Class 0.Interface/CertificadoRepImpl {
}
Class 0.Interface/LoggingImpl {
}
Class 0.Interface/InscripcionRepImpl {
}
Class 0.Interface/GrupoRepImpl {
}
Class 0.Interface/CursoRepImpl {
}
Class 0.Interface/Tipo_cursoRepImpl {
}
Class 0.Interface/LoggingImpl {
}
Class 0.Interface/InscripcionRepImpl {
}
Class 0.Interface/GrupoRepImpl {
}
Class 0.Interface/CursoRepImpl {
}
Class 0.Interface/Tipo_cursoRepImpl {
}
Class 0.Interface/LoggingImpl {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/GeneroRepController {
}
Class 0.NEWInstance/EstadoRepController {
}
Class 0.NEWInstance/Grado_profesorRepController {
}
Class 0.NEWInstance/TurnoRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/GeneroRepController {
}
Class 0.NEWInstance/EstadoRepController {
}
Class 0.NEWInstance/Grado_profesorRepController {
}
Class 0.NEWInstance/TurnoRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProcessorProfesorController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/GeneroRepController {
}
Class 0.NEWInstance/EstadoRepController {
}
Class 0.NEWInstance/Grado_profesorRepController {
}
Class 0.NEWInstance/TurnoRepController {
}
Class 0.NEWInstance/ProfesorRepController {
}
Class 0.NEWInstance/ProfesorDtoController {
}
}
package 1 <<Folder>> {
Class 1.Inscripcion {
}
Class 1.ConsultaInscripcionController {
}
Class 1.ProcessorInscripcion {
}
Class 1.InscripcionesController {
}
Class 1.ModificarInscripcion {
}
Class 1.InscripcionRep {
}
Class 1.InscripcionDto {
}
Class 1./DTO/Grupo {
}
Class 1.Request/Impl/GrupoRequestImpl {
}
Class 1./DTO/Profesor {
}
Class 1.Request/Impl/ProfesorRequestImpl {
}
Class 1.NEWInstance/InscripcionRepController {
}
Class 1.NEWInstance/InscripcionRepController {
}
Class 1.Interface/ProfesorRepImpl {
}
Class 1./DTO/Curso {
}
Class 1.Interface/CursoRepImpl {
}
Class 1.Interface/GrupoRepImpl {
}
Class 1.Interface/CertificadoRepImpl {
}
Class 1.Interface/ProfesorRepImpl {
}
Class 1.Interface/GrupoRepImpl {
}
Class 1.Interface/CursoRepImpl {
}
Class 1.Interface/GrupoRepImpl {
}
Class 1.Interface/ProfesorRepImpl {
}
Class 1.Interface/LoggingImpl {
}
Class 1.Interface/ProfesorRepImpl {
}
Class 1.Interface/GrupoRepImpl {
}
Class 1.Interface/CursoRepImpl {
}
Class 1.Interface/GeneroRepImpl {
}
Class 1.Interface/EstadoRepImpl {
}
Class 1.Interface/Grado_profesorRepImpl {
}
Class 1.Interface/Tipo_cursoRepImpl {
}
Class 1.Interface/TurnoRepImpl {
}
Class 1.Interface/LoggingImpl {
}
Class 1.NEWInstance/InscripcionRepController {
}
Class 1.NEWInstance/InscripcionRepController {
}
Class 1.NEWInstance/InscripcionRepController {
}
Class 1.NEWInstance/InscripcionRepController {
}
Class 1.NEWInstance/ProcessorInscripcionController {
}
Class 1.NEWInstance/InscripcionRepController {
}
Class 1.NEWInstance/InscripcionDtoController {
}
Class 1./DTO/Certificado {
}
}
package 2 <<Folder>> {
Class 2.Certificado {
}
Class 2.DescargasController {
}
Class 2.ClienteCertificadoController {
}
Class 2.CertificadoMasivoController {
}
Class 2.Logging {
}
Class 2.Log_sysRep {
}
Class 2.Log_evento_sysRep {
}
Class 2.Log_sys {
}
Class 2.Url_wsRep {
}
Class 2.Url_ws {
}
Class 2.Log_evento_sys {
}
Class 2.AuditoriasController {
}
Class 2.CertificadoRep {
}
Class 2.SeguridadPDF {
}
Class 2./DTO/Usuario_sys {
}
Class 2.Request/Impl/Usuario_sysRequestImpl {
}
Class 2./DTO/Profesor {
}
Class 2.Request/Impl/ProfesorRequestImpl {
}
Class 2./DTO/Curso {
}
Class 2.Request/Impl/CursoRequestImpl {
}
Class 2./DTO/Grupo {
}
Class 2.Request/Impl/GrupoRequestImpl {
}
Class 2.NEWInstance/CertificadoRepController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/CertificadoRepController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.Interface/InscripcionRepImpl {
}
Class 2.Interface/ProfesorRepImpl {
}
Class 2.Interface/ProfesorRepImpl {
}
Class 2.Interface/CursoRepImpl {
}
Class 2.Interface/GrupoRepImpl {
}
Class 2.Interface/ProfesorRepImpl {
}
Class 2.Interface/CursoRepImpl {
}
Class 2.Interface/GrupoRepImpl {
}
Class 2.Interface/Usuario_sysRepImpl {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2.NEWInstance/LoggingController {
}
Class 2./DTO/Inscripcion {
}
}
package 3 <<Folder>> {
Class 3.Grupo {
}
Class 3.BatchController {
}
Class 3.ProcessorGrupo {
}
Class 3.GrupoController {
}
Class 3.ModificarGrupos {
}
Class 3.GrupoRep {
}
Class 3.ConsultaGrupoController {
}
Class 3.ReaderGrupo {
}
Class 3.GrupoDto {
}
Class 3./DTO/Curso {
}
Class 3.Request/Impl/CursoRequestImpl {
}
Class 3./DTO/Profesor {
}
Class 3.Request/Impl/ProfesorRequestImpl {
}
Class 3./DTO/Inscripcion {
}
Class 3.Request/Impl/InscripcionRequestImpl {
}
Class 3./DTO/Certificado {
}
Class 3.Request/Impl/CertificadoRequestImpl {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.Interface/CursoRepImpl {
}
Class 3.Interface/ProfesorRepImpl {
}
Class 3.Interface/InscripcionRepImpl {
}
Class 3.Interface/SendMailServiceImpl {
}
Class 3.Interface/CursoRepImpl {
}
Class 3.Interface/ProfesorRepImpl {
}
Class 3.Interface/CursoRepImpl {
}
Class 3.Interface/ProfesorRepImpl {
}
Class 3.Interface/LoggingImpl {
}
Class 3.Interface/ProfesorRepImpl {
}
Class 3.Interface/InscripcionRepImpl {
}
Class 3.Interface/CursoRepImpl {
}
Class 3.Interface/GeneroRepImpl {
}
Class 3.Interface/EstadoRepImpl {
}
Class 3.Interface/Grado_profesorRepImpl {
}
Class 3.Interface/Tipo_cursoRepImpl {
}
Class 3.Interface/TurnoRepImpl {
}
Class 3.Interface/LoggingImpl {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.NEWInstance/ProcessorGrupoController {
}
Class 3.NEWInstance/GrupoRepController {
}
Class 3.NEWInstance/GrupoRepController {
}
}
package 4 <<Folder>> {
Class 4.WebService {
}
Class 4.Url_ws_profesorRep {
}
Class 4.Url_ws_cursoRep {
}
Class 4.Url_ws_inscripcionRep {
}
Class 4.ReturnTypeOne {
}
Class 4.ReturnTypeTwo {
}
Class 4.ReturnTypeThree {
}
Class 4.Url_ws_profesor {
}
Class 4.Url_ws_curso {
}
Class 4.Url_ws_inscripcion {
}
Class 4.Interface/ProfesorRepImpl {
}
Class 4.Interface/GrupoRepImpl {
}
Class 4.Interface/CursoRepImpl {
}
Class 4.Interface/InscripcionRepImpl {
}
Class 4.Interface/LoggingImpl {
}
Class 4./DTO/Profesor {
}
Class 4./DTO/Curso {
}
Class 4./DTO/Grupo {
}
}
package 5 <<Folder>> {
Class 5.BatchConfig {
}
Class 5.WriterCurso {
}
Class 5.CursoBatchRep {
}
Class 5.WriterGrupo {
}
Class 5.GrupoBatchRep {
}
Class 5.WriterInscripcion {
}
Class 5.InscripcionBatchRep {
}
Class 5.ProfesorBatchRep {
}
Class 5.WriterProfesor {
}
Class 5.Interface/ProcessorGrupoImpl {
}
Class 5.Interface/ProcessorCursoImpl {
}
Class 5.Interface/ProcessorInscripcionImpl {
}
Class 5.Interface/ProcessorProfesorImpl {
}
}
package 6 <<Folder>> {
Class 6.ModificarCursos {
}
Class 6.CursoRep {
}
Class 6.Tipo_cursoRep {
}
Class 6.Curso {
}
Class 6.Tipo_curso {
}
Class 6.ConsultaController {
}
Class 6.ProcessorCurso {
}
Class 6.ConsultaCursoController {
}
Class 6.CursosController {
}
Class 6.ReaderCurso {
}
Class 6.CursoDto {
}
Class 6.ExcelConfig {
}
Class 6.CursoExcelRowMapper {
}
Class 6.LoggingCursoProcessor {
}
Class 6./DTO/Grupo {
}
Class 6.Request/Impl/GrupoRequestImpl {
}
Class 6./DTO/Grupo {
}
Class 6.Request/Impl/GrupoRequestImpl {
}
Class 6./DTO/Certificado {
}
Class 6.Request/Impl/CertificadoRequestImpl {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/Tipo_cursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/Tipo_cursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/Tipo_cursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/Tipo_cursoRepController {
}
Class 6.NEWInstance/CursoRepController {
}
Class 6.NEWInstance/ProcessorCursoController {
}
Class 6.Interface/ProfesorRepImpl {
}
Class 6.Interface/InscripcionRepImpl {
}
Class 6.Interface/GrupoRepImpl {
}
Class 6.Interface/GeneroRepImpl {
}
Class 6.Interface/EstadoRepImpl {
}
Class 6.Interface/Grado_profesorRepImpl {
}
Class 6.Interface/TurnoRepImpl {
}
Class 6.Interface/LoggingImpl {
}
Class 6.Interface/ProfesorRepImpl {
}
Class 6.Interface/GrupoRepImpl {
}
Class 6.Interface/LoggingImpl {
}
Class 6.NEWInstance/CursoDtoController {
}
}
package 7 <<Folder>> {
Class 7.Usuario_sysRep {
}
Class 7.AltaUsuarios {
}
Class 7.RecuperaContrasena {
}
Class 7.EditarPerfil {
}
Class 7.Usuario_sys {
}
Class 7.Estatus_usuario_sys {
}
Class 7.Perfil_sys {
}
Class 7.MyAppUserDetailsService {
}
Class 7.SendMailService {
}
Class 7.ExampleContoller {
}
Class 7.Estatus_usuario_sysRep {
}
Class 7.Perfil_sysRep {
}
Class 7.SecurityConfig {
}
Class 7./DTO/Log_sys {
}
Class 7.Request/Impl/Log_sysRequestImpl {
}
Class 7.NEWInstance/Usuario_sysRepController {
}
Class 7.NEWInstance/SendMailServiceController {
}
Class 7.Interface/LoggingImpl {
}
Class 7.Interface/LoggingImpl {
}
Class 7.Interface/LoggingImpl {
}
Class 7.NEWInstance/SendMailServiceController {
}
Class 7.NEWInstance/SendMailServiceController {
}
}
package 8 <<Folder>> {
Class 8.CargaBatchService {
}
Class 8.ResponseGeneric {
}
Class 8.CargaBatchServiceImpl {
}
Class 8.ejemploServiceImpl {
}
Class 8.ejemploService {
}
Class 8.CorreoServiceImpl {
}
Class 8.CorreoService {
}
Class 8.AvisosCorreoDAO {
}
Class 8.CargaBatchServiceDAO {
}
Class 8.ErroresDTO {
}
Class 8.FiltroCorreoDTO {
}
Class 8.ResponseGenericPagination {
}
Class 8.Interface/SendMailServiceImpl {
}
Class 8.Interface/SendMailServiceImpl {
}
Class 8.Interface/CursoDtoImpl {
}
Class 8.Interface/ProfesorDtoImpl {
}
Class 8.Interface/InscripcionDtoImpl {
}
}
@enduml
