@startuml
package 0 <<Folder>> {
Class 0.PatientService {
}
Class 0.PatientWaitingAppointmentService {
}
Class 0.MakeAppointment {
}
Class 0.Patient {
}
Class 0.User {
}
Class 0.PatientWaitingAppointment {
}
Class 0.WaitingAppointmentController {
}
Class 0.AppointmentMsgController {
}
Class 0.DoctorReceptionistController {
}
Class 0.PatientServiceImpl {
}
Class 0.PatientWaitingAppointmentServiceImpl {
}
Class 0.PatientRepository {
}
Class 0.PatientWaitingAppointmentRepository {
}
Class 0.UserController {
}
Class 0.ReceptionistAdmin {
}
Class 0.UserService {
}
Class 0.UserValidationService {
}
Class 0.RegistrationService {
}
Class 0.CustomAuthenticationProvider {
}
Class 0.PublicController {
}
Class 0.UserServiceImpl {
}
Class 0.RegistrationController {
}
Class 0.UserValidationServiceImpl {
}
Class 0.RegistrationServiceImpl {
}
Class 0.HospitalFormatter {
}
Class 0.UserRepository {
}
Class 0.ImageUploadService {
}
Class 0.ImageUploadServiceImpl {
}
Class 0.WebSecurityConfig {
}
Class 0.IAuthenticationFacade {
}
Class 0.AuthenticationFacade {
}
Class 0.Receptionist {
}
Class 0.Employee {
}
Class 0.VerificarVagas {
}
Class 0.ReceptionistService {
}
Class 0.ReceptionistRepository {
}
Class 0.ReceptionistServiceImpl {
}
Class 0.Doctor {
}
Class 0.UnitResponsible {
}
Class 0.DoctorService {
}
Class 0.DoctorController {
}
Class 0.DoctorServiceImpl {
}
Class 0.DoctorRepository {
}
Class 0./DTO/Slot {
}
Class 0.Request/Impl/SlotRequestImpl {
}
Class 0./DTO/Message {
}
Class 0.Request/Impl/MessageRequestImpl {
}
Class 0./DTO/Appointment {
}
Class 0.Request/Impl/AppointmentRequestImpl {
}
Class 0./DTO/Speciality {
}
Class 0.Request/Impl/SpecialityRequestImpl {
}
Class 0./DTO/Slot {
}
Class 0.Request/Impl/SlotRequestImpl {
}
Class 0.Interface/SlotServiceImpl {
}
Class 0.Interface/MessageServiceImpl {
}
Class 0.Interface/SpecialityServiceImpl {
}
Class 0.Interface/CommonImpl {
}
Class 0.Interface/CommonImpl {
}
Class 0.Interface/SlotServiceImpl {
}
Class 0.Interface/AppointmentServiceImpl {
}
Class 0.Interface/CommonImpl {
}
Class 0.Interface/AppointmentServiceImpl {
}
Class 0./DTO/DoctorWaitingPatient {
}
Class 0.Interface/DoctorWaitingPatientServiceImpl {
}
Class 0.Interface/SpecialityServiceImpl {
}
Class 0./DTO/Nationality {
}
Class 0.Interface/NationalityServiceImpl {
}
Class 0.Interface/SlotServiceImpl {
}
Class 0.Interface/DoctorWaitingPatientServiceImpl {
}
Class 0.Interface/InvoiceServiceImpl {
}
Class 0.Interface/CommonImpl {
}
Class 0.Interface/CommonImpl {
}
Class 0.Interface/NationalityServiceImpl {
}
Class 0.Interface/NationalityRepositoryImpl {
}
Class 0.Interface/SpecialityRepositoryImpl {
}
Class 0.Interface/SpecialityServiceImpl {
}
Class 0.Interface/SlotServiceImpl {
}
Class 0.Interface/MessageServiceImpl {
}
Class 0.Interface/AppointmentServiceImpl {
}
Class 0.Interface/CommonImpl {
}
Class 0.Interface/SpecialityRepositoryImpl {
}
Class 0.Interface/AppointmentRepositoryImpl {
}
Class 0.Interface/DoctorWaitingPatientRepositoryImpl {
}
Class 0.Interface/InvoiceServiceImpl {
}
Class 0.Interface/MessageServiceImpl {
}
Class 0.NEWInstance/UserServiceController {
}
Class 0.NEWInstance/PatientWaitingAppointmentServiceController {
}
Class 0.NEWInstance/UserValidationServiceController {
}
Class 0.NEWInstance/RegistrationServiceController {
}
Class 0.NEWInstance/DoctorServiceController {
}
Class 0.NEWInstance/PatientServiceController {
}
Class 0.NEWInstance/PatientWaitingAppointmentServiceController {
}
Class 0.NEWInstance/MakeAppointmentController {
}
Class 0.NEWInstance/PatientWaitingAppointmentServiceController {
}
Class 0.NEWInstance/UserServiceController {
}
Class 0.NEWInstance/PatientServiceController {
}
Class 0.NEWInstance/DoctorServiceController {
}
Class 0.NEWInstance/PatientWaitingAppointmentServiceController {
}
Class 0.NEWInstance/DoctorServiceController {
}
Class 0.NEWInstance/DoctorRepositoryController {
}
Class 0.NEWInstance/UserServiceController {
}
Class 0.NEWInstance/PatientServiceController {
}
Class 0.NEWInstance/UserServiceController {
}
Class 0.NEWInstance/UserServiceController {
}
Class 0.NEWInstance/UserServiceController {
}
}
package 1 <<Folder>> {
Class 1.ReceptionistController {
}
Class 1.SlotService {
}
Class 1.SlotValidationService {
}
Class 1.Day {
}
Class 1.Slot {
}
Class 1.TimeInterval {
}
Class 1.Calendar {
}
Class 1.PatientController {
}
Class 1.CreateSlots {
}
Class 1.SlotServiceImpl {
}
Class 1.SlotValidationServiceImpl {
}
Class 1.SlotRepository {
}
Class 1./DTO/Appointment {
}
Class 1.Request/Impl/AppointmentRequestImpl {
}
Class 1./DTO/Doctor {
}
Class 1.Request/Impl/DoctorRequestImpl {
}
Class 1./DTO/PatientWaitingAppointment {
}
Class 1.Request/Impl/PatientWaitingAppointmentRequestImpl {
}
Class 1.NEWInstance/SlotServiceController {
}
Class 1.NEWInstance/SlotServiceController {
}
Class 1.NEWInstance/SlotServiceController {
}
Class 1.NEWInstance/SlotServiceController {
}
Class 1./DTO/Speciality {
}
Class 1.Interface/SpecialityServiceImpl {
}
Class 1.Interface/UserServiceImpl {
}
Class 1./DTO/Nationality {
}
Class 1.Interface/NationalityServiceImpl {
}
Class 1./DTO/MakeAppointment {
}
Class 1.Interface/AppointmentServiceImpl {
}
Class 1.Interface/PatientWaitingAppointmentServiceImpl {
}
Class 1.Interface/SpecialityValidationServiceImpl {
}
Class 1.Interface/UserValidationServiceImpl {
}
Class 1.Interface/RegistrationServiceImpl {
}
Class 1.Interface/DoctorServiceImpl {
}
Class 1.Interface/PatientServiceImpl {
}
Class 1.Interface/PatientWaitingAppointmentServiceImpl {
}
Class 1.Interface/CommonImpl {
}
Class 1.Interface/MakeAppointmentImpl {
}
Class 1.Interface/MessageServiceImpl {
}
Class 1.Interface/AppointmentServiceImpl {
}
Class 1.Interface/PatientWaitingAppointmentServiceImpl {
}
Class 1.Interface/SpecialityServiceImpl {
}
Class 1.Interface/UserServiceImpl {
}
Class 1.Interface/PatientServiceImpl {
}
Class 1.Interface/DoctorServiceImpl {
}
Class 1.Interface/PatientWaitingAppointmentServiceImpl {
}
Class 1.Interface/CommonImpl {
}
Class 1.Interface/DoctorServiceImpl {
}
Class 1.Interface/DoctorRepositoryImpl {
}
Class 1./DTO/UserValidationService {
}
Class 1./DTO/User {
}
Class 1./DTO/SpecialityValidationService {
}
}
package 2 <<Folder>> {
Class 2.SpecialityService {
}
Class 2.SpecialityValidationService {
}
Class 2.Speciality {
}
Class 2.SpecialityServiceImpl {
}
Class 2.SpecialityValidationServiceImpl {
}
Class 2.SpecialityRepository {
}
Class 2./DTO/Doctor {
}
Class 2.Request/Impl/DoctorRequestImpl {
}
Class 2.NEWInstance/SpecialityServiceController {
}
Class 2.NEWInstance/SpecialityServiceController {
}
Class 2.NEWInstance/SpecialityRepositoryController {
}
Class 2.NEWInstance/SpecialityServiceController {
}
Class 2.NEWInstance/SpecialityRepositoryController {
}
Class 2.NEWInstance/SpecialityServiceController {
}
Class 2.NEWInstance/SpecialityValidationServiceController {
}
Class 2.NEWInstance/SpecialityServiceController {
}
Class 2.NEWInstance/SpecialityServiceController {
}
Class 2.NEWInstance/SpecialityServiceController {
}
}
package 3 <<Folder>> {
Class 3.NationalityService {
}
Class 3.Nationality {
}
Class 3.NationalityServiceImpl {
}
Class 3.NationalityRepository {
}
Class 3.NEWInstance/NationalityServiceController {
}
Class 3.NEWInstance/NationalityServiceController {
}
Class 3.NEWInstance/NationalityRepositoryController {
}
Class 3.NEWInstance/NationalityServiceController {
}
}
package 4 <<Folder>> {
Class 4.AppointmentService {
}
Class 4.Appointment {
}
Class 4.AppointmentListController {
}
Class 4.CheckInController {
}
Class 4.UpdateInvoice {
}
Class 4.AppointmentServiceImpl {
}
Class 4.AppointmentRepository {
}
Class 4.CloseAppointment {
}
Class 4./DTO/Patient {
}
Class 4.Request/Impl/PatientRequestImpl {
}
Class 4./DTO/Slot {
}
Class 4.Request/Impl/SlotRequestImpl {
}
Class 4.NEWInstance/AppointmentServiceController {
}
Class 4.NEWInstance/AppointmentServiceController {
}
Class 4.NEWInstance/AppointmentServiceController {
}
Class 4.NEWInstance/AppointmentRepositoryController {
}
Class 4.NEWInstance/AppointmentServiceController {
}
Class 4.NEWInstance/AppointmentServiceController {
}
Class 4./DTO/Speciality {
}
Class 4.Interface/SpecialityServiceImpl {
}
Class 4.Interface/UserServiceImpl {
}
Class 4.Interface/PatientServiceImpl {
}
Class 4.Interface/CommonImpl {
}
Class 4.Interface/UserServiceImpl {
}
Class 4.Interface/SpecialityServiceImpl {
}
Class 4.Interface/CommonImpl {
}
Class 4.Interface/InvoiceServiceImpl {
}
Class 4.NEWInstance/AppointmentRepositoryController {
}
Class 4./DTO/User {
}
Class 4./DTO/DoctorWaitingPatient {
}
}
package 5 <<Folder>> {
Class 5.Common {
}
Class 5.MessageService {
}
Class 5.Message {
}
Class 5.MessageController {
}
Class 5.MyErrorController {
}
Class 5.MessageRestController {
}
Class 5.MessageServiceImpl {
}
Class 5.MessageRepository {
}
Class 5./DTO/User {
}
Class 5.Request/Impl/UserRequestImpl {
}
Class 5.NEWInstance/MessageServiceController {
}
Class 5.NEWInstance/CommonController {
}
Class 5.NEWInstance/CommonController {
}
Class 5.NEWInstance/CommonController {
}
Class 5.NEWInstance/CommonController {
}
Class 5.NEWInstance/CommonController {
}
Class 5.NEWInstance/MessageServiceController {
}
Class 5.NEWInstance/CommonController {
}
Class 5.NEWInstance/MessageServiceController {
}
Class 5.NEWInstance/CommonController {
}
Class 5.NEWInstance/MessageServiceController {
}
Class 5.NEWInstance/CommonController {
}
Class 5.NEWInstance/CommonController {
}
Class 5.NEWInstance/CommonController {
}
Class 5.Interface/UserServiceImpl {
}
Class 5.NEWInstance/CommonController {
}
}
package 6 <<Folder>> {
Class 6.InvoiceController {
}
Class 6.Invoice {
}
Class 6.InvoiceService {
}
Class 6.InvoiceServiceImpl {
}
Class 6.InvoiceApi {
}
Class 6.InvoiceFilter {
}
Class 6.InvoiceItem {
}
Class 6.InvoiceListResponse {
}
Class 6.InvoiceResponse {
}
Class 6.InvoiceRepository {
}
Class 6.NEWInstance/InvoiceServiceController {
}
Class 6.NEWInstance/InvoiceServiceController {
}
Class 6.NEWInstance/InvoiceServiceController {
}
Class 6.Interface/UserServiceImpl {
}
Class 6.Interface/CommonImpl {
}
Class 6.Interface/AppointmentRepositoryImpl {
}
Class 6./DTO/Appointment {
}
}
package 7 <<Folder>> {
Class 7.DoctorWaitingPatient {
}
Class 7.DoctorWaitingPatientService {
}
Class 7.DoctorWaitingPatientRepository {
}
Class 7.DoctorWaitingPatientServiceImpl {
}
Class 7.NEWInstance/DoctorWaitingPatientServiceController {
}
Class 7.NEWInstance/DoctorWaitingPatientServiceController {
}
Class 7.NEWInstance/DoctorWaitingPatientRepositoryController {
}
}
@enduml
